version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
    restart: always
  go-app:
    image: golang:1.21
    ports:
      - "8080:8080"
    working_dir: /app
    command: go run main.go
    volumes:
      - .:/app
  redis:
    image: redis:7.0.15-alpine3.20
    ports:
      - "6380:6380"
    volumes:
      - redis-data:/data
    restart: always
  db:
    image: public.ecr.aws/docker/library/postgres:16
    ports:
      - 5433:5433
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/postgres
      o: bind
  redis-data:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/redis
      o: bind
